.PHONY = all clean

all: chessgame

chessgame: main.cpp board.cpp square.cpp piece.cpp pawn.cpp knight.cpp bishop.cpp rook.cpp
	g++ main.cpp board.cpp square.cpp piece.cpp pawn.cpp knight.cpp bishop.cpp rook.cpp -o prog 
#clean:
#	@echo "Cleaning executable..."
#	rm .\prog.txt